go run main.go testFiles/example00.txt
go run main.go testFiles/example01.txt
go run main.go testFiles/example02.txt
go run main.go testFiles/example03.txt
go run main.go testFiles/example04.txt
go run main.go testFiles/example05.txt
go run main.go testFiles/example06.txt
go run main.go testFiles/example07.txt
go run main.go testFiles/badexample00.txt
go run main.go testFiles/badexample01.txt