go run main.go examples/example00.txt
go run main.go examples/example01.txt
go run main.go examples/example02.txt
go run main.go examples/example03.txt
go run main.go examples/example04.txt
go run main.go examples/example05.txt
go run main.go examples/example06.txt
go run main.go examples/example07.txt
go run main.go examples/badexample00.txt
go run main.go examples/badexample01.txt
